default_language_version:
  python: python3.8

fail_fast: true # stops executing subsequent hooks if one hook fails

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        args: [-l 100, -v]
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--docstring-convention=google, --max-line-length=100]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.901
    hooks:
      - id: mypy

  - repo: https://github.com/terraform-linters/tflint
    rev: v0.29.0
    hooks:
      - id: tflint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.8
    hooks:
      - id: commitizen
        stages: [commit-msg]
