default_language_version:
  python: python3.8

default_stages: [commit]

fail_fast: true # stops executing subsequent hooks if one hook fails

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-json

  #TODO: remove black
  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--docstring-convention=google, --max-line-length=88]

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.8.1
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy

  - repo: https://github.com/terraform-linters/tflint
    rev: v0.28.0
    hooks:
      - id: tflint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
