version: 2.1

jobs:
  lint-code:
    docker:
      - image: magicbeanbuyer/circleci-images:1.7.0
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: "install git hook"
          command: pre-commit install --hook-type pre-commit
      - run:
          name: "lint code and commit message"
          command: |
            pre-commit run --hook-stage manual --from-ref << pipeline.git.base_revision >> --to-ref << pipeline.git.revision >>
            cz check --rev-range << pipeline.git.base_revision >>..<< pipeline.git.revision >>
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

workflows:
  main:
    jobs:
      - lint-code:
          name: "lint code"
          context: [DOCKER_HUB]
