version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  lint-code:
    executor: python/default
    steps:
      - checkout
      - run:
          name: "check path"
          command: |
            echo $PWD
            echo $(ls)
      #      - run:
      #          name: "install golang"
      #          command: |
      #            sudo apt install software-properties-common gpg
      #            sudo add-apt-repository ppa:longsleep/golang-backports
      #            sudo apt update
      #            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F6BC817356A3D45E
      #            sudo apt install golang-go
      #      - run:
      #          name: "install pre-commit and commitizen"
      #          command: ./git_enhancement.sh circleci
      #      - run:
      #          name: "lint code and commit message"
      #          command: |
      #            pre-commit run --hook-stage manual --from-ref << pipeline.git.base_revision >> --to-ref << pipeline.git.revision >>
      #            cz check --rev-range << pipeline.git.base_revision >>..<< pipeline.git.revision >>
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  check-data-persistance:
    executor: python/default
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "temp"
          command: |
            echo $PWD
            echo $(ls)
            cd project
            echo $(ls)

workflows:
  main:
    jobs:
      - lint-code
      - check-data-persistance
