version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: echo $CIRCLE_COMPARE_URL "\n" << pipeline.git.revision >> "\n" << pipeline.git.base_revision >>

workflows:
  main:
    jobs:
      - build-and-test
