version: 2.1

jobs:
  lint-code:
    docker:
      - image: magicbeanbuyer/circleci-images:1.9.0
        auth:
          username: $USERNAME
          password: $PASSWORD
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: "lint code and commit message"
          command: .circleci/bin/code_and_commit_linter.sh
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  check-data-persistance:
    docker:
      - image: magicbeanbuyer/circleci-images:1.9.0
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "temp"
          command: |
            echo $PWD
            echo $(ls)

workflows:
  main:
    jobs:
      - lint-code:
          name: "lint code"
          context: [DOCKER_HUB]
      - check-data-persistance:
          name: "check data persistence"
          context: [DOCKER_HUB]
          requires:
            - "lint code"
