version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          - name: "install golang"
          - command: |
              sudo apt install software-properties-common gpg
              sudo add-apt-repository ppa:longsleep/golang-backports
              sudo apt update
              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F6BC817356A3D45E
              sudo apt install golang-go
      - run:
          - name: "pre-commit hook"
          - command: ./git_enhancement.sh circleci
#              pip install pre-commit
#              pre-commit install
#              pre-commit run --from-ref << pipeline.git.base_revision >> --to-ref << pipeline.git.revision >>

workflows:
  main:
    jobs:
      - build-and-test
