version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  lint-code:
    executor: python/default
    steps:
      - checkout

      - run:
          name: "install pre-commit hook"
          command: pre-commit install --hook-type pre-commit
      - run:
          name: "lint code and commit message"
          command: |
            pre-commit run --hook-stage manual --from-ref << pipeline.git.base_revision >> --to-ref << pipeline.git.revision >>
            cz check --rev-range << pipeline.git.base_revision >>..<< pipeline.git.revision >>

workflows:
  main:
    jobs:
      - lint-code
